//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsClient.WcfServer.V1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/WcfServer.Results")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WsClient.WcfServer.V1.ResultOfCommandDto3K_SeiaR2))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfCommandDto3K_SeiaR2", Namespace="http://schemas.datacontract.org/2004/07/WcfServer.Results")]
    [System.SerializableAttribute()]
    public partial class ResultOfCommandDto3K_SeiaR2 : WsClient.WcfServer.V1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WsClient.WcfServer.V1.CommandDto ResultObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WsClient.WcfServer.V1.CommandDto ResultObject {
            get {
                return this.ResultObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultObjectField, value) != true)) {
                    this.ResultObjectField = value;
                    this.RaisePropertyChanged("ResultObject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandDto", Namespace="http://schemas.datacontract.org/2004/07/WcfServer.V1.Dtos")]
    [System.SerializableAttribute()]
    public partial class CommandDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParamsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Params {
            get {
                return this.ParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamsField, value) != true)) {
                    this.ParamsField = value;
                    this.RaisePropertyChanged("Params");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMessageCommandDto", Namespace="http://schemas.datacontract.org/2004/07/WcfServer.V1.Dtos")]
    [System.SerializableAttribute()]
    public partial class SendMessageCommandDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThemeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskName {
            get {
                return this.TaskNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskNameField, value) != true)) {
                    this.TaskNameField = value;
                    this.RaisePropertyChanged("TaskName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Theme {
            get {
                return this.ThemeField;
            }
            set {
                if ((object.ReferenceEquals(this.ThemeField, value) != true)) {
                    this.ThemeField = value;
                    this.RaisePropertyChanged("Theme");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateFileCommandDto", Namespace="http://schemas.datacontract.org/2004/07/WcfServer.V1.Dtos")]
    [System.SerializableAttribute()]
    public partial class CreateFileCommandDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskName {
            get {
                return this.TaskNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskNameField, value) != true)) {
                    this.TaskNameField = value;
                    this.RaisePropertyChanged("TaskName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServer.V1.ICommandService")]
    public interface ICommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/GetCommand", ReplyAction="http://tempuri.org/ICommandService/GetCommandResponse")]
        WsClient.WcfServer.V1.ResultOfCommandDto3K_SeiaR2 GetCommand(string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/GetCommand", ReplyAction="http://tempuri.org/ICommandService/GetCommandResponse")]
        System.Threading.Tasks.Task<WsClient.WcfServer.V1.ResultOfCommandDto3K_SeiaR2> GetCommandAsync(string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/Done", ReplyAction="http://tempuri.org/ICommandService/DoneResponse")]
        WsClient.WcfServer.V1.Result Done(System.Guid commandId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/Done", ReplyAction="http://tempuri.org/ICommandService/DoneResponse")]
        System.Threading.Tasks.Task<WsClient.WcfServer.V1.Result> DoneAsync(System.Guid commandId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/Fail", ReplyAction="http://tempuri.org/ICommandService/FailResponse")]
        WsClient.WcfServer.V1.Result Fail(System.Guid commandId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/Fail", ReplyAction="http://tempuri.org/ICommandService/FailResponse")]
        System.Threading.Tasks.Task<WsClient.WcfServer.V1.Result> FailAsync(System.Guid commandId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/AddSendMessageTask", ReplyAction="http://tempuri.org/ICommandService/AddSendMessageTaskResponse")]
        WsClient.WcfServer.V1.Result AddSendMessageTask(WsClient.WcfServer.V1.SendMessageCommandDto command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/AddSendMessageTask", ReplyAction="http://tempuri.org/ICommandService/AddSendMessageTaskResponse")]
        System.Threading.Tasks.Task<WsClient.WcfServer.V1.Result> AddSendMessageTaskAsync(WsClient.WcfServer.V1.SendMessageCommandDto command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/AddCreateFileTask", ReplyAction="http://tempuri.org/ICommandService/AddCreateFileTaskResponse")]
        WsClient.WcfServer.V1.Result AddCreateFileTask(WsClient.WcfServer.V1.CreateFileCommandDto command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/AddCreateFileTask", ReplyAction="http://tempuri.org/ICommandService/AddCreateFileTaskResponse")]
        System.Threading.Tasks.Task<WsClient.WcfServer.V1.Result> AddCreateFileTaskAsync(WsClient.WcfServer.V1.CreateFileCommandDto command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/Ping", ReplyAction="http://tempuri.org/ICommandService/PingResponse")]
        WsClient.WcfServer.V1.Result Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/Ping", ReplyAction="http://tempuri.org/ICommandService/PingResponse")]
        System.Threading.Tasks.Task<WsClient.WcfServer.V1.Result> PingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommandServiceChannel : WsClient.WcfServer.V1.ICommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommandServiceClient : System.ServiceModel.ClientBase<WsClient.WcfServer.V1.ICommandService>, WsClient.WcfServer.V1.ICommandService {
        
        public CommandServiceClient() {
        }
        
        public CommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WsClient.WcfServer.V1.ResultOfCommandDto3K_SeiaR2 GetCommand(string clientName) {
            return base.Channel.GetCommand(clientName);
        }
        
        public System.Threading.Tasks.Task<WsClient.WcfServer.V1.ResultOfCommandDto3K_SeiaR2> GetCommandAsync(string clientName) {
            return base.Channel.GetCommandAsync(clientName);
        }
        
        public WsClient.WcfServer.V1.Result Done(System.Guid commandId) {
            return base.Channel.Done(commandId);
        }
        
        public System.Threading.Tasks.Task<WsClient.WcfServer.V1.Result> DoneAsync(System.Guid commandId) {
            return base.Channel.DoneAsync(commandId);
        }
        
        public WsClient.WcfServer.V1.Result Fail(System.Guid commandId) {
            return base.Channel.Fail(commandId);
        }
        
        public System.Threading.Tasks.Task<WsClient.WcfServer.V1.Result> FailAsync(System.Guid commandId) {
            return base.Channel.FailAsync(commandId);
        }
        
        public WsClient.WcfServer.V1.Result AddSendMessageTask(WsClient.WcfServer.V1.SendMessageCommandDto command) {
            return base.Channel.AddSendMessageTask(command);
        }
        
        public System.Threading.Tasks.Task<WsClient.WcfServer.V1.Result> AddSendMessageTaskAsync(WsClient.WcfServer.V1.SendMessageCommandDto command) {
            return base.Channel.AddSendMessageTaskAsync(command);
        }
        
        public WsClient.WcfServer.V1.Result AddCreateFileTask(WsClient.WcfServer.V1.CreateFileCommandDto command) {
            return base.Channel.AddCreateFileTask(command);
        }
        
        public System.Threading.Tasks.Task<WsClient.WcfServer.V1.Result> AddCreateFileTaskAsync(WsClient.WcfServer.V1.CreateFileCommandDto command) {
            return base.Channel.AddCreateFileTaskAsync(command);
        }
        
        public WsClient.WcfServer.V1.Result Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<WsClient.WcfServer.V1.Result> PingAsync() {
            return base.Channel.PingAsync();
        }
    }
}
